### PR TITLE
PREF-271 | write to log when DEBUG_MODE

### PR DESCRIPTION
**Pull request by nico-spada-virtasant**
## Change Notes
- Added support to log extra errors to /Logs/HTTP.log  using DEBUG_MODE
- Included errors related to build HTTP containers.
- Added template for PR

## JIRA Issues
- [PREF-271](https://55places.atlassian.net/browse/PREF-271)

### CODE REVIEW

**Review by harshpatel991 — APPROVED** [review]

**Comment by harshpatel991** [comment]
Can you let Yuca know of the changes that you made so he can make the same changes on the 8.x branch?

**Comment by nico-spada-virtasant** [comment]
Hi @Firtzberg , just to let it know that this PR includes modifications that we want to have in Prefab8. we will create tickets for this later at the moment I'm just adding you as reference. Thanks.

**Comment by Firtzberg** [comment]
@harshpatel991 Should this be included in 8.0 or should we release 8.0 without this and then have 8.1?

**Comment by harshpatel991** [comment]
@Firtzberg I think its fine to put it in 8.1 as long as its soon after 8.0 is released since you're already very close to releasing 8.0

**Comment by nico-spada-virtasant** [comment]
Closing this in favor of [PR-236](https://github.com/neighborhoods/Prefab/pull/236). It is the same feature but implemented in Prefab 8.

**Pull request closed without merging**
